name: osc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pinocchio=3.3.1
  - pip
  - pip:
      - numpy==1.26.4
      - pybullet==3.2.5
      - pybullet-data
      - scipy==1.13.1
      - -e git+https://github.com/huggingface/lerobot.git#egg=lerobot[smolvla]
